---
development:
  cloud_name: hgxjzznzo
  api_key: '388437281755167'
  api_secret: Exh8n15QGWqmCrbTEvr5T39S9a0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hgxjzznzo
  api_key: '388437281755167'
  api_secret: Exh8n15QGWqmCrbTEvr5T39S9a0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hgxjzznzo
  api_key: '388437281755167'
  api_secret: Exh8n15QGWqmCrbTEvr5T39S9a0
  enhance_image_tag: true
  static_file_support: false
